export const VIEWS = {
  FOOD_EXERCISE_INPUT: "FOOD_EXERCISE_INPUT",
  FOOD_INPUT: "FOOD_INPUT",
  EXERCISE_INPUT: "EXERCISE_INPUT",
  FOOD_RESULT_DETAIL: "FOOD_RESULT_DETAIL",
  CHAT_ROOM: "CHAT_ROOM",
  PROFILE: "PROFILE",
  LOGIN_PAGE: "LOGIN_PAGE",
  SETTINGS: "SETTINGS",
  SOCIAL_PAGE: "SOCIAL_PAGE",
  NEW_MESSAGE: "NEW_MESSAGE",
  ONBOARDING: "ONBOARDING"
}
